version: '3'

services:
  db:
    image: mysql:latest
    container_name: TaskMicroService
    env_file:
      - Homework_09.env
    ports:
      - "3308:3306"
    volumes:
      - ./database:/var/lib/mysql
