# Определение используемого образа Docker
image: alpine:latest

# Определение этапов пайплайна
stages:
  - test
  - deploy

# Определение задач для каждого этапа
test:
  stage: test
  script:
# Проверка доступности страницы
    - curl --fail http://$CI_PAGES_URL || exit 1

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r ./CICD/homework_01/web/* .public
  artifacts:
    paths:
      - .public

# Определение настройки Pages
pages:
  stage: deploy
  script:
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
