spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3307/Homework
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: User
      password: Password
